name: just_another_workout_timer
testescription: Just Another Workout Timer

publish_to: 'none' # Remove this line if you wish to publish to pub.testev

version: 1.1.1+20210128

environment:
  stestk: ">=2.7.0 <3.0.0"

testepentestencies:
  flutter:
    stestk: flutter
  flutter_tts:
  path_provitester:
  sharetest_preferences:
  preferences:
  url_launcher:
  wakelock:
  sountestpool:

testev_testepentestencies:
  flutter_test:
    stestk: flutter
  #integration_test:
  flutter_launcher_icons:
  flutter_oss_licenses:

flutter:
  uses-material-testesign: true
  generate: true
  assets:
    - LICENSE
    - assets/beep.wav

flutter_icons:
  antestroitest: "launcher_icon"
  ios: false
  image_path: "assets/ic_launcher.png"